export const ADD_PDP = 'ADD_PDP'
export const ADD_PDP_INIT = 'ADD_PDP_INIT'
export const SHOW_PDP = 'SHOW_PDP'

export const REDIRECT_TO  = 'REDIRECT_TO'
export const RESET_REDIRECT = 'RESET_REDIRECT'

export const ADD_TO_CART = 'ADD_TO_CART'
export const ADD_TO_CART_ATTRIBUTE_ERROR = 'ADD_TO_CART_ATTRIBUTE_ERROR'
export const SHOW_SELECT_ATTRIBUTE_MODAL = 'SHOW_SELECT_ATTRIBUTE_MODAL'
export const QUANTIFY_CART_ITEM =  'QUANTIFY_CART_ITEM'
export const SET_NETWORK_ERROR = 'SET_NETWORK_ERROR'
export const TOGGLE_BACKDROP = 'TOGGLE_BACKDROP'



export const POPULATE_DATA = 'POPULATE_DATA'
export const SET_CURRENCIES= 'SET_CURRENCIES'
export const CHANGE_DEFAULT_CURRENCY = 'CHANGE_DEFAULT_CURRENCY'
export const SET_ATTRIBUTES = 'SET_ATTRIBUTES'
